localStorage.setItem("ders","Javascript");
// console.log(localStorage.getItem("ders")) //! local storage içindeki value değerini console'a yazdırmak için...
// localStorage.removeItem("ders") //! value silmek için...